### ISSUE TITLE
Upcoming Features and Suggestions

### ISSUE THREAD

**Issue by RednedEpic** [BattlePlugins/BattleArena#106]
I was thinking about making a new post or editing #14, but since there are no plans of recoding the whole plugin and making a "v4.0 version" yet, I've decided to create a new issue containing a list of what I plan on tackling this summer. I'll try my best to implement anything already suggested and any new suggestions people may have. 

Ideas which are currently higher priority are mainly listed at the top. Some ideas are elaborated on below so people have a better idea on what to expect.

<h2>Work in Progress Features and Ideas</h2>

***Progress:***
- [x] MySQL Support
- [ ] BungeeCord Support (follow progress [here](https://github.com/BattlePlugins/BattleArena/tree/bungee))
- [x] PlaceholderAPI Support
- [x] Custom Signs (#76)
- [x] Title, Subtitle and ActionBar Support
- [ ] Medley Option/Gamemode (#90)
- [ ] Translatable and Toggleable Messages with API for Extensions (#14, #80, #99)
- [ ] Per-Arena Classes (#22)
- [x] Arena Regeneration (#22)
- [ ] More Integrations with Modern Plugins (e.g. Quality Armory #101)
- [ ] Cleaner, More Consistent Command Messages and Hover Events (#53)
- [ ] Invisible Spectators (#14)
- [ ] More Victory Conditions
- [ ] Better Item Serialization for Modern Items (NBT, attributes, etc.)

<h3>More Information:</h3>

***BungeeCord and MySQL Support:*** (Adapted From #14)
This is one of the the most requested features: "Bungeecord support." What this means is that when players are teleported from the lobby to the arena, they could also potentially be teleported to a different server. (Obviously configurable to also support a single server setup).

For this all to work properly, a basic MySQL system has to be implemented. The way BattleArena will manage BungeeCord support is when a server starts up, all its game information will be broadcasted to the database. 

When you run a command such as /arena j, instead of just checking the server you're on for active games, it will check all the active games broadcasted VIA MySQL and see if there is anything running. 

Not only will MySQL be handy for BungeeCord, you can also hook into MySQL to see if there are any games active by other means such as a website! This can be especially handy if you want to create a small web system that views where the player currently is on your server. You can use it to find what server they're on, what game they're playing, the game status and who else is in the game with them.

***PlaceholderAPI Support:***
This feature already exists for BattleTracker, however it is planned to be implemented into BattleArena too. It's usage here will be so you can view information such as what arena a player is in, who is in the game with them, how long the game has been running for, etc.

***Medley:*** (From #90)
Medley is a mixture of game types: Instead of joining one game type, you can join a Medley and it'll be a random (or queue'd) game type after each match: DeathMatch, CaptureTheFlag, Domination/Conquest/Control, Sabotage/SearchNDestroy, HostageArena, BlutoniumArena, etc.

As always, if anyone has any suggestions or would like to add on to what is said here, please feel free to comment. Suggestions are always welcome 😃.

**Comment by RednedEpic** [comment]
After more consideration and attempts to implement these features, I have decided to go ahead with a rewrite with many of the same goals and ideas of #14. The rewrite will feature most (if not all) of the features in this issue as well, as well as a cleaned up arena format. A more in-depth issue will be opened at a future date.
